//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdwih.Jobs.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentPosition
    {
        public EmploymentPosition()
        {
            this.Awards = new HashSet<Award>();
            this.PositionDuties = new HashSet<PositionDuty>();
        }
    
        public long id { get; set; }
        public long ResumeId { get; set; }
        public string Title { get; set; }
        public string SupervisorPhone { get; set; }
        public string SupervisorName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public short NumberOWeeklyHours { get; set; }
        public bool IsVolunteerPosition { get; set; }
        public bool IsInPresentPosition { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<PositionDuty> PositionDuties { get; set; }
        public virtual PersonResume PersonResume { get; set; }
    }
}
