//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdwih.Jobs.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonReferences = new HashSet<PersonReference>();
            this.PhoneNumbers = new HashSet<PhoneNumber>();
            this.PersonResumes = new HashSet<PersonResume>();
        }
    
        public long PersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public short Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        public virtual ICollection<PersonReference> PersonReferences { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
        public virtual ICollection<PersonResume> PersonResumes { get; set; }
    }
}
