//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdwih.Jobs.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonReference
    {
        public long PersonResumeId { get; set; }
        public long PersonId { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PersonResume PersonResume { get; set; }
    }
}
