//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hdwih.Jobs.Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonResume
    {
        public PersonResume()
        {
            this.EmploymentPositions = new HashSet<EmploymentPosition>();
            this.LanguageSpokens = new HashSet<LanguageSpoken>();
            this.PersonEducations = new HashSet<PersonEducation>();
            this.PersonReferences = new HashSet<PersonReference>();
            this.SkillOrSpecialities = new HashSet<SkillOrSpeciality>();
        }
    
        public long PersonResumeId { get; set; }
        public string Name { get; set; }
        public long PersonId { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
    
        public virtual ICollection<EmploymentPosition> EmploymentPositions { get; set; }
        public virtual ICollection<LanguageSpoken> LanguageSpokens { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<PersonEducation> PersonEducations { get; set; }
        public virtual ICollection<PersonReference> PersonReferences { get; set; }
        public virtual ICollection<SkillOrSpeciality> SkillOrSpecialities { get; set; }
    }
}
